### ISSUE TITLE
Request does not finish

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#165] opened 2016-11-24 08:21 UTC
http://api.freme-project.eu/current/e-entity/freme-ner/documents?language=en&dataset=dbpedia&informat=text&mode=link&input=Wild+Atlantic+Way&outformat=turtle

It loads for a long time but never finishes and produces no result.

It used to work before, see #129

Probably this is the same error as #164

**Comment by sandroacoelho** [comment] 2016-11-25 05:19
Hi @jnehring ,

The bug was in our [NIFParser](https://github.com/NLP2RDF/NIF-lib/blob/0.3/src/main/java/org/nlp2rdf/parser/NIFParser.java#L29) . I fixed it, so could you please update our FREME-DEV/Live?

Btw, it solves our #164 issue

Thanks,

**Comment by fsasaki** [comment] 2016-11-25 06:19
I now get with this requets

 curl -X POST --header 'Content-Type: text/plain' --header 'Accept:
text/turtle' -d 'Berlin' '
https://api-dev.freme-project.eu/current/e-entity/freme-ner/documents?language=en&dataset=dbpedia&mode=all
'

the following error


{ "exception":
"eu.freme.bservices.filter.proxy.exception.BadGatewayException", "path":
"/e-entity/freme-ner/documents", "message": "Proxy failed:
org.apache.http.conn.HttpHostConnectException: Connect to
rv2622.1blu.de:7001 [rv2622.1blu.de/178.254.20.8] failed: Connection
refused", "error": "Bad Gateway", "status": 502, "timestamp": 1480054601569
}


the same error occurs with mode=link

@jnehring, is this related to this bug?

2016-11-25 6:19 GMT+01:00 Sandro <notifications@github.com>:

**Comment by borriellom** [comment] 2016-11-25 10:01
I'm getting the same error on both dev and live versions. Any news on this?

**Comment by fsasaki** [comment] 2016-11-25 10:25
@m1ci and @sandroacoelho , do you see a way to solve this without Jan? It seems the bug influences other demos as well, also without the use of the link mode. See

https://github.com/freme-project/freme-ner/issues/163#issuecomment-262924453

**Comment by fsasaki** [comment] 2016-11-25 10:36
Actually all demos using FREME-NER seem to fail now, see e.g. also
https://freme-project.github.io/freme-showcase/ease-of-adaption.html

**Comment by sandroacoelho** [comment] 2016-11-25 12:29
@borriellom @fsasaki The FREME-NER was not running on the server. I have started it right now and will check why the process has stopped . Could please check if it is ok now?

**Comment by fsasaki** [comment] 2016-11-25 12:56
works, thanks!

2016-11-25 13:29 GMT+01:00 Sandro <notifications@github.com>:

**Comment by borriellom** [comment] 2016-11-25 14:30
Yes, it works now. Thanks!!!

**Comment by jnehring** [comment] 2016-11-29 08:31
Thanks for the fix! This bug is fixed on freme-dev but not on freme-live. I will leave the issue open to check if is fixed after the next release.

**Comment by jnehring** [comment] 2017-01-12 13:57
The problem still exists on freme-live and it is fixed on freme-dev. Meanwhile I have released all parts of freme.

**Comment by m1ci** [comment] 2017-01-18 12:46
http://api.freme-project.eu/current/e-entity/freme-ner/documents?language=en&dataset=dbpedia&informat=text&mode=link&input=Wild+Atlantic+Way&outformat=turtle
works and the issue is fixed on freme live

**Closed by m1ci** 2017-01-18 12:46 UTC
Labels: bug
