### ISSUE TITLE
wrong content type in the response

### ISSUE THREAD

**Issue by m1ci** [freme-project/freme-ner#103] opened 2016-05-19 13:17 UTC
I just noticed that FREME NER returns wrong content type header.
The response is formatted in the correct format, but the content type header is wrong. 
Try this link in the browser
http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents/?informat=text&input=Diego%20Maradona&outformat=turtle&language=en&dataset=dbpedia
and check the content type header.

I think this bug was introduced with the architecture update.

**Comment by jnehring** [comment] 2016-05-20 07:15
I can confirm the bug. It does not happen on e-terminology and e-translation. @bgrusdt please fix the problem.

**Comment by ArneBinder** [comment] 2016-07-01 16:59
Does this also happen if the freme worker (rv2622.1blu.de:7001) is called directly? 
```
http://rv2622.1blu.de:7001/e-entity/freme-ner/documents/?informat=text&input=Diego%20Maradona&outformat=turtle&language=en&dataset=dbpedia
```
If not, this bug is caused by the proxy-filter.

**Comment by bgrusdt** [comment] 2016-07-04 10:36
I only see this behaviour when the call is made from the browser, then it returns the response content-type text/html.  With Postman it returns, text/plain. 
When I call it with my local installation, it returns text/turtle as expected. But when I call it locally from  the browser  ``` http://localhost:7001/e-entity/freme-ner/documents/?informat=text&input=Diego%20Maradona&outformat=turtle&language=en&dataset=dbpedia ``` , the response content-type is correct, i.e. text/turtle.

**Comment by jnehring** [comment] 2016-07-11 11:45
probably related issue is https://github.com/freme-project/basic-services/issues/37

**Comment by bgrusdt** [comment] 2016-07-11 13:17
This should be fixed with this [commit](https://github.com/freme-project/basic-services/commit/fd039515a65cfca6a7a810af9be467575cc3c21f).

**Closed by bgrusdt** 2016-07-11 13:17 UTC
Labels: bug
