### ISSUE TITLE
Research dataset licenses

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#153] opened 2016-09-15 08:54 UTC
From [making FREME assets available](https://docs.google.com/document/d/1qlA2LyqKwGeO_ds9hFNDzKT_Wd_C7wv6z4CIK_PLiSo/edit#)

Does the licensing allow to re-distribute the datasets? Research for each dataset.

**Comment by m1ci** [comment] 2016-09-19 12:22
done, see the "license" column of the "List of FREME datasets" table.

**Comment by jnehring** [comment] 2016-09-21 07:35
I see that you added the license to each dataset but I cannot find the information if the license allows re-distribution or not.

**Comment by m1ci** [comment] 2016-09-21 07:47
while it is clear for CC licenses, some dataset use "custom" licenses. E.g.

- cordis - https://ec.europa.eu/info/legal-notice_en - its not clear if we can or cannot re-distribute.
- geopolitical ontology - http://www.fao.org/contact-us/terms/en/ - probably we can re-distribute.
- global airports - quite unclear, here they write that there is fee for commercial use (http://openflights.org/data.html#license) but the data is publised under ODL license (http://opendatacommons.org/licenses/odbl/1.0/) which says "allow users to freely share, modify, and use this Database while maintaining this same freedom for others".
- VIAF - https://datahub.io/dataset/viaf - under Open Data Commons Attribution license - which means we can re-distribute (http://opendatacommons.org/licenses/by/summary/)
- the license for Europeana is still unclear

**Comment by jnehring** [comment] 2016-09-22 13:47
So we can re-distribute CC licenses. I just read about geopolitical ontology, the readme you posted says:

Content may be adapted, translated, copied, printed and downloaded for private study, research and teaching purposes, and for use in commercial and non-commercial products or services, provided that appropriate acknowledgement of FAO as the source s given and that FAO's endorsement of users' views, products or services is not stated or implied in any way.

So we just need to add in a readme file a link to the source. We need to research the other datasets as well.

**Comment by m1ci** [comment] 2017-01-18 12:44
the issue is fixed, licensing info has been collected and documented. closing the issue

**Closed by m1ci** 2017-01-18 12:44 UTC
Labels: question
