### ISSUE TITLE
linking method produces error

### ISSUE THREAD

**Issue by fsasaki** [freme-project/freme-ner#164] opened 2016-11-23 16:31 UTC
Request is

>  curl -X POST --header 'Content-Type: text/plain' --header 'Accept: text/turtle' -d 'Berlin' 'https://api.freme-project.eu/current/e-entity/freme-ner/documents?language=en&dataset=dbpedia&mode=link'

I get

> {
  "exception": "eu.freme.common.exception.ExternalServiceFailedException",
  "path": "/e-entity/freme-ner/documents",
  "message": "We apologise for some inconvenience, but seems that the server is to busy too answer your request. Could you please try again in some minutes? Thanks ",
  "error": "Bad Gateway",
  "status": 502,
  "timestamp": 1479918515166
}

with the mode "all" there is no issue.

**Comment by jnehring** [comment] 2016-11-24 08:25
The behaviour is different when I try the request: The request takes forever and does never finish. But I get a bug also.

**Comment by sandroacoelho** [comment] 2016-11-25 12:49
@fsasaki : mode spot, link, classify enabled in FREME-NER dev. Could you please test again?

Thanks

**Comment by fsasaki** [comment] 2016-11-25 12:57
it works on FREME dev. On live it does not yet work. Should we keep this open for FREME live? @jnehring

**Comment by jnehring** [comment] 2016-11-29 08:32
I will leave the issue open to check again after next release if it is also fixed on live.

**Comment by jnehring** [comment] 2016-12-15 10:12
The bug is fixed on dev, but even after the release the curl request does not work on freme-live.

**Comment by m1ci** [comment] 2016-12-15 10:22
Can you try to do the same what Sandro did for FREME dev -> enable spot, link, classify

**Comment by jnehring** [comment] 2016-12-15 11:02
What should I do exactly? Is this a configuration option?

**Comment by jnehring** [comment] 2016-12-15 11:03
Hm... actually I think I did not release freme-ner. Maybe this is the issue.

**Comment by jnehring** [comment] 2017-01-12 13:56
The problem still happens on freme-live although I released FREME ner.

**Comment by m1ci** [comment] 2017-01-18 12:46
> curl -X POST --header 'Content-Type: text/plain' --header 'Accept: text/turtle' -d 'Berlin' 'https://api.freme-project.eu/current/e-entity/freme-ner/documents?language=en&dataset=dbpedia&mode=link'

works, the issue is fixed, closing the issue

**Closed by m1ci** 2017-01-18 12:46 UTC
Labels: bug
